# Generated by Django 6.0.2 on 2026-03-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_shoesize_size_shoeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoeimage',
            name='firebase_path',
        ),
        migrations.RemoveField(
            model_name='shoeimage',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='shoeimage',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shoeimage',
            name='image_url',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
