# Generated by Django 6.0.2 on 2026-03-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_shoeimage_firebase_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoeimage',
            name='image_url',
            field=models.ImageField(upload_to='shoes/'),
        ),
    ]
