# Generated by Django 6.0.2 on 2026-03-02 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_shoeimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='soletype',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sole_types', to='app.brand'),
        ),
        migrations.AlterUniqueTogether(
            name='soletype',
            unique_together={('name', 'brand')},
        ),
    ]
