# Generated by Django 6.0.2 on 2026-03-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_soletype_brand_alter_soletype_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soletype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
