# Generated by Django 6.0.2 on 2026-03-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_size_remove_shoe_sole_type_shoevariant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='soletype',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='soletype',
            name='brand',
        ),
    ]
